### ISSUE TITLE
CTC Decoder is not working

### ISSUE THREAD

**Issue by LuluW8071** [LuluW8071/Speech-Recognition#16]
```
Processing d:\repository\ctcdecode
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "D:\Repository\Speech Recognition\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Repository\Speech Recognition\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Repository\Speech Recognition\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\shash\AppData\Local\Temp\pip-build-env-f1mlfcsz\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\shash\AppData\Local\Temp\pip-build-env-f1mlfcsz\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\shash\AppData\Local\Temp\pip-build-env-f1mlfcsz\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\shash\AppData\Local\Temp\pip-build-env-f1mlfcsz\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Affects entire speech recognition engine**

**Comment by LuluW8071** [comment]
### Alternative needed #11

**Comment by LuluW8071** [comment]
Alternative List:
https://github.com/githubharald/CTCDecoder

**Comment by LuluW8071** [comment]
@404saugat404 https://github.com/parlance/ctcdecode/issues/182 
Check 2nd comment

Need solution asap

**Comment by LuluW8071** [comment]
**Potential solution**
https://stackoverflow.com/questions/64206712/ctcdecode-install-fail-command-python-setup-py-egg-info-failed-with-error-co

**Comment by LuluW8071** [comment]
@SabalM 
**Depedencies**
Install visual studio c++ build tools from Microsoft
And select c++ build option to download

**Comment by SabalM** [comment]
- Used **Ubuntu 22.04.3 LTS** in virtual machine
- Installed **Python 3.10.12** , pip3 , git
- Installed **Pytorch Stable(2.1.1) for CPU**
- Cloned repository:  [https://github.com/parlance/ctcdecode.git](https://github.com/parlance/ctcdecode.git)
- CTC decoder failed install
- Cloned repository (recursive):  [https://github.com/Sushmitha-Deva/ctcdecode.git](https://github.com/Sushmitha-Deva/ctcdecode.git)
- CTC decoder successfully installed with following code:
```
sabharjan@sabuntu:-$ cd ctcdecode
sabharjan@sabuntu:~/ctcdecode$ pip install
Defaulting to user installation because normal site-packages is not writeable
Processing /home/sabharjan/ctcdecode
Preparing metadata (setup.py)... done
Building wheels for collected packages: ctcdecode
Building wheel for ctcdecode (setup.py)... done
Created wheel for ctcdecode: filename=ctcdecode-1.0.4-cp310-cp310-linux_x86_64.whl size=27797466sha256=5f0b2fbd75fd5059e1549531475a06249b25076e8f302a67515688f164efaf9d
Stored in directory: /tmp/pip-ephen-wheel-cache-puhmdp5l/wheels/de/53/9a/bd42a063a0e2ec62e80c20baadf5dd15594b2c36ece9552b37
Successfully built ctcdecode
Installing collected packages: ctcdecode
Successfully installed ctcdecode-1.0.4
```
- Then received error while importing ctcdeocde with following code:
```
>> import torch
>> import ctcdecode
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/sabharjan/ctcdecode/ctcdecode/_init__.py", line 6, in <module> from_ext import ctc_decode
ModuleNotFoundError: No module named 'ctcdecode._ext'
```

**Comment by LuluW8071** [comment]
Try `cd ..` : move out of ctcdecode directory. Then again import torch and ctcdecode
```
import torch
import ctcdecode 
```

**Comment by LuluW8071** [comment]
> * Used **Ubuntu 22.04.3 LTS** in virtual machine
> * Installed **Python 3.10.12** , pip3 , git
> * Installed **Pytorch Stable(2.1.1) for CPU**
> * Cloned repository:  https://github.com/parlance/ctcdecode.git
> * CTC decoder failed install
> * Cloned repository (recursive):  https://github.com/Sushmitha-Deva/ctcdecode.git
> * CTC decoder successfully installed with following code:
> 
> ```
> sabharjan@sabuntu:-$ cd ctcdecode
> sabharjan@sabuntu:~/ctcdecode$ pip install
> Defaulting to user installation because normal site-packages is not writeable
> Processing /home/sabharjan/ctcdecode
> Preparing metadata (setup.py)... done
> Building wheels for collected packages: ctcdecode
> Building wheel for ctcdecode (setup.py)... done
> Created wheel for ctcdecode: filename=ctcdecode-1.0.4-cp310-cp310-linux_x86_64.whl size=27797466sha256=5f0b2fbd75fd5059e1549531475a06249b25076e8f302a67515688f164efaf9d
> Stored in directory: /tmp/pip-ephen-wheel-cache-puhmdp5l/wheels/de/53/9a/bd42a063a0e2ec62e80c20baadf5dd15594b2c36ece9552b37
> Successfully built ctcdecode
> Installing collected packages: ctcdecode
> Successfully installed ctcdecode-1.0.4
> ```
> 
> * Then received error while importing ctcdeocde with following code:
> 
> ```
> >> import torch
> >> import ctcdecode
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "/home/sabharjan/ctcdecode/ctcdecode/_init__.py", line 6, in <module> from_ext import ctc_decode
> ModuleNotFoundError: No module named 'ctcdecode._ext'
> ```

Try `cd ..` : move out of ctcdecode directory. Then again import torch and ctcdecode
```
import torch
import ctcdecode 
```

**Comment by SabalM** [comment]
![Screenshot from 2023-12-07 11-37-51](https://github.com/LuluW8071/Speech-Recognition/assets/60474591/2bfafc7f-488d-4f2b-ac69-a9c1f503bd26)

**Comment by LuluW8071** [comment]
CURRENTLY working on Ubuntu
