### ISSUE TITLE
KenLM Build

### ISSUE THREAD

**Issue by LuluW8071** [LuluW8071/Speech-Recognition#18]
https://kheafield.com/code/kenlm/dependencies/

**Comment by SabalM** [comment]
```lmplz -o 1 vocab.txt 3glm.arpa```
```bin/lmplz -o 1 <path/to/text_file> <path/to/save/language/model>```
![Screenshot from 2023-12-07 11-33-53](https://github.com/LuluW8071/Speech-Recognition/assets/60474591/ce9cc812-e522-44a7-94af-8f33482a8841)

**Comment by LuluW8071** [comment]
```lmplz -o n vocab.txt nglm.arpa ```
```bin/lmplz -o n <path/to/.txt> <path/save/language/model.arpa>```

Where,
`-o n` is order of words to select at once when building kenlm
`nglm.arpa` name for arpa file for llm 
if `-o 1` give name `1glm.arpa` and so on for better readability.

Completed in PR #19

**Comment by LuluW8071** [comment]
Merged and Documented in PR #19
